export const tiposPlaca = [
  { value: " ", label: " - PARTICULAR" },
  {
    value: "TAP",
    label: "TAP-AEROPUERTO INTERNACIONAL  JUAN SANTAMARIA",
  },
  {
    value: "352",
    label: "352-AGENCIA DE PROTECCION DE DATOS DE LOS HABITANTES",
  },
  { value: "AB", label: "AB-ALAJUELA BUS" },
  { value: "AP", label: "AP-ALAJUELA PUBLICO" },
  { value: "AL", label: "AL-ASAMBLEA LEGISLATIVA" },
  { value: "PEB", label: "PEB-ASAMBLEA LEGISLATIVA" },
  { value: "339", label: "339-ASAMBLEA LEGISLATIVA." },
  {
    value: "316",
    label: "316-ASOCIACION DE CONSERVACION Y DESARROLLO FORESTAL DE TALAMANCA",
  },
  {
    value: "297",
    label: "297-AUTORIDAD REGULADORA DE LOS SERVICIOS PUBLICOS",
  },
  { value: "051", label: "051-BANCO ANGLO COSTARRRICENSE" },
  { value: "052", label: "052-BANCO CENTRAL DE COSTA RICA" },
  { value: "053", label: "053-BANCO CREDITO AGRICOLA DE CARTAGO" },
  { value: "054", label: "054-BANCO DE COSTA RICA" },
  { value: "305", label: "305-BANCO HIPOTECARIO DE LA VIVIENDA" },
  { value: "055", label: "055-BANCO NACIONAL DE COSTA RICA" },
  { value: "056", label: "056-BANCO POPULAR Y DE DESARROLLO COMUNAL" },
  { value: "BTA", label: "BTA-BICICLETA" },
  { value: "BM", label: "BM-BICIMOTO" },
  { value: "200", label: "200-CAJA COSTARRICENSE DEL SEGURO SOCIAL" },
  { value: "CL", label: "CL-CARGA LIVIANA" },
  { value: "C", label: "C-CARGA PESADA" },
  { value: "CB", label: "CB-CARTAGO BUS" },
  { value: "CP", label: "CP-CARTAGO PUBLICO" },
  {
    value: "325",
    label: "325-CENTRO COSTARRICENSE DE PRODUCCION CINEMATOGRAFICA",
  },
  {
    value: "327",
    label: "327-CENTRO CULTURAL E HISTORICO JOSE FIGUERES FERRER",
  },
  { value: "326", label: "326-CENTRO NACIONAL DE LA MUSICA" },
  { value: "111", label: "111-CLUBES 4 - S" },
  { value: "311", label: "311-COLEGIO UNIVERSITARIO DE ALAJUELA" },
  { value: "01", label: "01-COLEGIO UNIVERSITARIO DE CARTAGO" },
  { value: "COL", label: "COL-COLEGIO UNIVERSITARIO DE CARTAGO" },
  { value: "314", label: "314-COLEGIO UNIVERSITARIO DE CARTAGO" },
  { value: "319", label: "319-COLEGIO UNIVERSITARIO DE LIMON" },
  { value: "312", label: "312-COLEGIO UNIVERSITARIO DE PUNTARENAS" },
  {
    value: "298",
    label:
      "298-COLEGIO UNIVERSITARIO PARA EL RIESGO Y EL DESARROLLO DEL TROPICO",
  },
  { value: "238", label: "238-COM.NAC.INVESTIGACION CIEN. Y TEC." },
  { value: "303", label: "303-COMISION DE ENERGIA ATOMICA DE C.R." },
  { value: "233", label: "233-COMISION NACIONAL DE ASUNTOS INDIGENAS" },
  {
    value: "057",
    label: "057-COMISION NACIONAL DE PRESTAMOS PARA LA EDUCACION",
  },
  {
    value: "322",
    label:
      "322-COMISION NACIONAL DE PREVENCION DE RIESGOS Y ATENCION EMERGENCIAS",
  },
  {
    value: "351",
    label:
      "351-COMISION PARA EL ORDENAMIENTO Y MANEJO DE LA CUENCA DEL RIO REVENTAZON",
  },
  {
    value: "353",
    label:
      "353-COMISIÓN NACIONAL PARA LA GESTION DE LA BIODIVERSIDAD (CONAGEBIO)",
  },
  { value: "107", label: "107-COMPAÑIA NACIONAL DE FUERZA Y LUZ" },
  { value: "CNF", label: "CNF-COMPAÑIA NACIONAL DE FUERZA Y LUZ" },
  { value: "012", label: "012-CONCESIONARIO DE OBRA PUBLICA" },
  { value: "344", label: "344-CONSEJO DE SALUD OCUPACIONAL" },
  { value: "260", label: "260-CONSEJO DE SEGURIDAD VIAL" },
  { value: "318", label: "318-CONSEJO DE TRANSPORTE PUBLICO" },
  { value: "323", label: "323-CONSEJO NACIONAL DE CONCESIONES" },
  {
    value: "328",
    label: "328-CONSEJO NACIONAL DE LA POLITICA PUBLICA DE LA PERSONA JOVEN",
  },
  {
    value: "240",
    label: "240-CONSEJO NACIONAL DE PERSONAS CON DISCAPACIDAD (CONAPDIS)",
  },
  { value: "100", label: "100-CONSEJO NACIONAL DE PRODUCCION" },
  { value: "239", label: "239-CONSEJO NACIONAL DE RECTORES" },
  { value: "CGR", label: "CGR-CONTRALORIA GENERAL DE LA REPUBLICA" },
  { value: "309", label: "309-CONTRATOS ACUEDUCTOS Y ALCANTARILLADO" },
  { value: "306", label: "306-CONTRATOS COMISION NAC. EMERGENCIA" },
  { value: "CRC", label: "CRC-CRUZ ROJA" },
  { value: "CC", label: "CC-CUERPO CONSULAR" },
  { value: "341", label: "341-CUERPO DE BOMBEROS DE COSTA RICA" },
  { value: "CD", label: "CD-CUERPO DIPLOMATICO" },
  {
    value: "D H",
    label: "D H-DEFENSORIA DE LOS HABITANTES DE LA REPUBLICA",
  },
  { value: "349", label: "349-DIRECCION NACIONAL DE NOTARIADO" },
  { value: "252", label: "252-EDITORIAL COSTA RICA" },
  { value: "EMB", label: "EMB-EMBAJADA DE LA REPUBLICA CHECA" },
  { value: "12", label: "12-EMPRESA CONSTRUCTORA" },
  {
    value: "101",
    label: "101-EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA",
  },
  { value: "EE", label: "EE-EQUIPO ESPECIAL" },
  { value: "302", label: "302-ESCUELA CENTROAMERICANA DE GANADERIA" },
  { value: "USA", label: "USA-ESTADOS UNIDOS DE AMERICA" },
  { value: "EXP", label: "EXP-EXPORTACION" },
  {
    value: "355",
    label: "355-FONDO DE NACIONAL DE FINANCIAMIENTO FORESTAL (FONAFIFO)",
  },
  { value: "350", label: "350-FONDO NACIONAL DE BECAS" },
  {
    value: "329",
    label:
      "329-FUNDACION AYUDANOS PARA AYUDAR (CENTRO COSTARRICENSE DE LA CIENCIA Y LA CULTURA)",
  },
  { value: "MI4", label: "MI4-FUNDACION CONSEJO DE LA TIERRA" },
  { value: "FUN", label: "FUN-FUNDACION FRIEDRICH EBERT" },
  { value: "GB", label: "GB-GUANACASTE BUS" },
  { value: "GP", label: "GP-GUANACASTE PUBLICO" },
  { value: "HB", label: "HB-HEREDIA BUS" },
  { value: "HP", label: "HP-HEREDIA PUBLICO" },
  { value: "264", label: "264-I.N.S.A." },
  { value: "259", label: "259-ILLANUT" },
  { value: "250", label: "250-IMPRENTA NACIONAL" },
  { value: "317", label: "317-INAMU" },
  { value: "110", label: "110-INS. COSTARRICENSE DE FERROCARRILES" },
  { value: "257", label: "257-INS. COSTARRICENSE DE TURISMO" },
  { value: "261", label: "261-INS. MIXTO DE AYUDA SOCIAL" },
  { value: "262", label: "262-INS. NACIONAL DE APRENDIZAJE" },
  { value: "265", label: "265-INS. TECNOLOGICO DE COSTA RICA" },
  { value: "258", label: "258-INST.GEOGRAFICO NACIONAL" },
  {
    value: "INC",
    label: "INC-INSTITUTO COSTARRICENES DE PESCA Y ACUACULTURA",
  },
  {
    value: "003",
    label: "003-INSTITUTO COSTARRICENSE CONTRA EL CANCER",
  },
  {
    value: "102",
    label: "102-INSTITUTO COSTARRICENSE DE ACUEDUCTOS Y ALCATARILLADOS",
  },
  { value: "103", label: "103-INSTITUTO COSTARRICENSE DE ELECTRICIDAD" },
  {
    value: "256",
    label:
      "256-INSTITUTO COSTARRICENSE DE INVESTIGACION Y ENSEÐANZA EN NUTRICION Y SALUD",
  },
  {
    value: "313",
    label: "313-INSTITUTO COSTARRICENSE DE PESCA Y ACUACULTURA",
  },
  { value: "263", label: "263-INSTITUTO DE DESARROLLO AGRARIO" },
  {
    value: "059",
    label: "059-INSTITUTO DE FOMENTO Y ASESORIA MUNICIPAL",
  },
  { value: "104", label: "104-INSTITUTO DE PUERTOS DEL PACIFICO" },
  { value: "IAG", label: "IAG-INSTITUTO GEODESICO AMERICANO" },
  {
    value: "113",
    label: "113-INSTITUTO NACIONAL DE ESTADISTICA Y CENSOS",
  },
  { value: "060", label: "060-INSTITUTO NACIONAL DE FOMENTO" },
  {
    value: "346",
    label:
      "346-INSTITUTO NACIONAL DE INNOVACION Y TRANSFERENCIA EN TECNOLOGIA AGROPECUARIA",
  },
  { value: "061", label: "061-INSTITUTO NACIONAL DE SEGUROS" },
  {
    value: "105",
    label: "105-INSTITUTO NACIONAL DE VIVIENDA Y URBANISMO",
  },
  { value: "109", label: "109-JUN.ADM.PUER.DES.ECON. VERT.ATLANTICA" },
  {
    value: "268",
    label: "268-JUNTA ADM. DIR. NAC. DE COMUNICACIONES   S",
  },
  { value: "331", label: "331-JUNTA ADMINISTRATIVA ARCHIVO NACIONAL" },
  {
    value: "108",
    label: "108-JUNTA ADMINISTRATIVA DE SERVICIOS ELECTRICOS DE CARTAGO",
  },
  {
    value: "332",
    label: "332-JUNTA ADMINISTRATIVA DEL MUSEO HISTORICO JUAN SANTAMARIA",
  },
  { value: "310", label: "310-JUNTA ADMINISTRATIVA REGISTRO NACIONAL" },
  {
    value: "333",
    label: "333-JUNTA ADMINISTRATIVA TEATRO MELICO SALAZAR",
  },
  { value: "315", label: "315-JUNTA ADMINISTRATIVA TEATRO NACIONAL" },
  { value: "330", label: "330-JUNTA ADMINISTRATIVA TEATRO NACIONAL" },
  {
    value: "273",
    label: "273-JUNTA DE PEN. Y JUB. MAGISTERIO NACIONAL",
  },
  { value: "276", label: "276-JUNTA PROTEC.SOCIAL SAN JOSE" },
  { value: "277", label: "277-JUNTA PROTEC.SOCIAL SAN RAMON" },
  { value: "LFP", label: "LFP-LIMITACIONES FISICAS PERMANENTES" },
  { value: "LB", label: "LB-LIMON BUS" },
  { value: "LP", label: "LP-LIMON PUBLICO" },
  { value: "MD", label: "MD-MISION DIPLOMATICA" },
  { value: "MI", label: "MI-MISION INTERNACIONAL" },
  { value: "MOT", label: "MOT-MOTOCICLETAS" },
  { value: "MF", label: "MF-MUNDIAL DE FUTBOL FEMENINO 2014" },
  { value: "335", label: "335-MUSEO DE ARTE COSTARRICENSE" },
  { value: "336", label: "336-MUSEO DE ARTE Y DISEÐO CONTEMPORANEO" },
  { value: "253", label: "253-MUSEO NACIONAL" },
  { value: "337", label: "337-MUSEO RAFAEL ANGEL CALDERON GUARDIA" },
  { value: "002", label: "002-MUTUALES DE AHORRO Y PRESTAMO" },
  { value: "OP", label: "OP-OBRA PUBLICA" },
  { value: "285", label: "285-OFICINA DEL ARROZ" },
  { value: "284", label: "284-OFICINA DEL CAFE" },
  { value: "286", label: "286-OFICINA NACIONAL DE SEMILLAS" },
  { value: "290", label: "290-PATRONATO NACIONAL DE LA INFANCIA" },
  { value: "292", label: "292-PATRONATO NACIONAL DE REHABILITACION" },
  { value: "PEN", label: "PEN-PENSIONADO" },
  { value: "TAX", label: "TAX-PERMISOS DE TAXI" },
  { value: "PE", label: "PE-PODER EJECUTIVO" },
  { value: "PJ", label: "PJ-PODER JUDICIAL" },
  {
    value: "112",
    label: "112-PROGRAMA INTEGRAL DE MERCADEO AGROPECUARIO (PIMA)",
  },
  { value: "PB", label: "PB-PUNTARENAS BUS" },
  { value: "PP", label: "PP-PUNTARENAS PUBLICO" },
  { value: "106", label: "106-RADIOGRAFICA COSTARRICENSE S.A." },
  {
    value: "308",
    label: "308-REFINADORA COSTARRICENSE DE PETROLEO (RECOPE)",
  },
  { value: "RL", label: "RL-REMOLQUE LIVIANO" },
  { value: "R", label: "R-REMOLQUES" },
  { value: "296", label: "296-S.E.N.A.R.A." },
  { value: "SJB", label: "SJB-SAN JOSE BUS" },
  { value: "SJP", label: "SJP-SAN JOSE PUBLICO" },
  { value: "S", label: "S-SEMIREMOLQUE" },
  { value: "SE", label: "SE-SERVICIO ESTABLE" },
  { value: "342", label: "342-SERVICIO FITOSANITARIO DEL ESTADO" },
  { value: "SM", label: "SM-SERVICIO MUNICIPAL" },
  { value: "340", label: "340-SERVICIO NACIONAL DE SALUD ANIMAL" },
  { value: "SR", label: "SR-SERVICIO REMOLQUE" },
  { value: "348", label: "348-SISTEMA DE BANCA PARA EL DESARROLLO" },
  { value: "324", label: "324-SISTEMA DE EMERGENCIAS 911" },
  {
    value: "347",
    label: "347-SISTEMA NACIONAL DE AREAS DE CONSERVACION",
  },
  {
    value: "338",
    label: "338-SISTEMA NACIONAL DE RADIO Y TELEVISION S.A. (SINART S.A.)",
  },
  {
    value: "345",
    label: "345-SUPERINTENDENCIA DE TELECOMUNICACIONES (SUTEL)",
  },
  { value: "TA", label: "TA-TAXI DE ALAJUELA" },
  { value: "TC", label: "TC-TAXI DE CARTAGO" },
  { value: "TG", label: "TG-TAXI DE GUANACASTE" },
  { value: "TH", label: "TH-TAXI DE HEREDIA" },
  { value: "TL", label: "TL-TAXI DE LIMON" },
  { value: "TP", label: "TP-TAXI DE PUNTARENAS" },
  { value: "TSJ", label: "TSJ-TAXI DE SAN JOSE" },
  { value: "TE", label: "TE-TAXI ESTABLE" },
  { value: "321", label: "321-TRIBUNAL ADMINISTRATIVO DE TRANSPORTES" },
  { value: "320", label: "320-TRIBUNAL REGISTRAL ADMINISTRATIVO" },
  { value: "TSE", label: "TSE-TRIBUNAL SUPREMO DE ELECCIONES" },
  { value: "TUR", label: "TUR-TURISMO" },
  { value: "301", label: "301-UNIVERSIDA NACIONAL" },
  {
    value: "307",
    label: "307-UNIVERSIDAD ADVENTISTA DE CENTRO AMERICA",
  },
  { value: "299", label: "299-UNIVERSIDAD DE COSTA RICA" },
  { value: "300", label: "300-UNIVERSIDAD ESTATAL A DISTANCIA" },
  { value: "343", label: "343-UNIVERSIDAD TECNICA NACIONAL" },
  { value: "VE", label: "VE-VEHICULO ESPECIAL" },
  { value: "VH", label: "VH-VEHICULO HISTORICO" },
  { value: "D", label: "D-VEHICULOS DISCAPACITADOS" },
  { value: "ZFE", label: "ZFE-ZONAS FRANCAS DE EXPORTACION" },
];
export const codigosPorTipo = {
  PE: [
    { value: "02", label: "02-CONTRALORIA GENERAL DE LA REPUBLICA" },
    { value: "11", label: "11-MIN. DE ECONOMIA, INDUSTRIA Y COMERCIO" },
    { value: "12", label: "12-MINIST. DE OBRAS PUBLICAS Y TRANSPORTES" },
    { value: "10", label: "10-MINISTERIO DE AGRICULTURA Y GANADERIA" },
    { value: "13", label: "13-MINISTERIO DE EDUCACION PUBLICA" },
    { value: "06", label: "06-MINISTERIO DE GOBERNACION" },
    { value: "19", label: "19-MINISTERIO DE JUSTICIA Y GRACIA" },
    { value: "17", label: "17-MINISTERIO DE JUVENTUD Y DEPORTES" },
    { value: "07", label: "07-MINISTERIO DE RELACIONES EXTERIORES" },
    { value: "14", label: "14-MINISTERIO DE SALUBRIDAD" },
    { value: "08", label: "08-MINISTERIO DE SEGURIDAD PUBLICA" },
    { value: "15", label: "15-MINISTERIO DE TRABAJO" },
    { value: "20", label: "20-PODER JUDICIAL" },
    { value: "05", label: "05-PRESIDENTE DE LA REPUBLICA" },
    { value: "25", label: "25-TRIBUNAL SUPREMO DE ELECCIONES" },
  ],
};

export const getCodigosParaTipo = (tipoPlaca) => {
  return codigosPorTipo[tipoPlaca] || null;
};